//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ICSI_UDIN.ICSI_SoapService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://tempuri.org/")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetMemberShipDataForGSTOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMemberDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMemberShipDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMemberDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMemberDetailsOnlineOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStudentDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStudentDetailsForeMSOPOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMemberNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStudentNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStudentDataOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::ICSI_UDIN.Properties.Settings.Default.ICSI_UDIN_ICSI_SoapService_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetMemberShipDataForGSTCompletedEventHandler GetMemberShipDataForGSTCompleted;
        
        /// <remarks/>
        public event GetMemberDataCompletedEventHandler GetMemberDataCompleted;
        
        /// <remarks/>
        public event GetMemberShipDataCompletedEventHandler GetMemberShipDataCompleted;
        
        /// <remarks/>
        public event GetMemberDetailsCompletedEventHandler GetMemberDetailsCompleted;
        
        /// <remarks/>
        public event GetMemberDetailsOnlineCompletedEventHandler GetMemberDetailsOnlineCompleted;
        
        /// <remarks/>
        public event GetStudentDetailsCompletedEventHandler GetStudentDetailsCompleted;
        
        /// <remarks/>
        public event GetStudentDetailsForeMSOPCompletedEventHandler GetStudentDetailsForeMSOPCompleted;
        
        /// <remarks/>
        public event GetMemberNameCompletedEventHandler GetMemberNameCompleted;
        
        /// <remarks/>
        public event GetStudentNameCompletedEventHandler GetStudentNameCompleted;
        
        /// <remarks/>
        public event GetStudentDataCompletedEventHandler GetStudentDataCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMemberShipDataForGST", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ICSI GetMemberShipDataForGST(string premember, int membno) {
            object[] results = this.Invoke("GetMemberShipDataForGST", new object[] {
                        premember,
                        membno});
            return ((ICSI)(results[0]));
        }
        
        /// <remarks/>
        public void GetMemberShipDataForGSTAsync(string premember, int membno) {
            this.GetMemberShipDataForGSTAsync(premember, membno, null);
        }
        
        /// <remarks/>
        public void GetMemberShipDataForGSTAsync(string premember, int membno, object userState) {
            if ((this.GetMemberShipDataForGSTOperationCompleted == null)) {
                this.GetMemberShipDataForGSTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMemberShipDataForGSTOperationCompleted);
            }
            this.InvokeAsync("GetMemberShipDataForGST", new object[] {
                        premember,
                        membno}, this.GetMemberShipDataForGSTOperationCompleted, userState);
        }
        
        private void OnGetMemberShipDataForGSTOperationCompleted(object arg) {
            if ((this.GetMemberShipDataForGSTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMemberShipDataForGSTCompleted(this, new GetMemberShipDataForGSTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMemberData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ICSI GetMemberData(string MemberShipNo, string DOB) {
            object[] results = this.Invoke("GetMemberData", new object[] {
                        MemberShipNo,
                        DOB});
            return ((ICSI)(results[0]));
        }
        
        /// <remarks/>
        public void GetMemberDataAsync(string MemberShipNo, string DOB) {
            this.GetMemberDataAsync(MemberShipNo, DOB, null);
        }
        
        /// <remarks/>
        public void GetMemberDataAsync(string MemberShipNo, string DOB, object userState) {
            if ((this.GetMemberDataOperationCompleted == null)) {
                this.GetMemberDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMemberDataOperationCompleted);
            }
            this.InvokeAsync("GetMemberData", new object[] {
                        MemberShipNo,
                        DOB}, this.GetMemberDataOperationCompleted, userState);
        }
        
        private void OnGetMemberDataOperationCompleted(object arg) {
            if ((this.GetMemberDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMemberDataCompleted(this, new GetMemberDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMemberShipData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ICSI GetMemberShipData(string premember, int membno) {
            object[] results = this.Invoke("GetMemberShipData", new object[] {
                        premember,
                        membno});
            return ((ICSI)(results[0]));
        }
        
        /// <remarks/>
        public void GetMemberShipDataAsync(string premember, int membno) {
            this.GetMemberShipDataAsync(premember, membno, null);
        }
        
        /// <remarks/>
        public void GetMemberShipDataAsync(string premember, int membno, object userState) {
            if ((this.GetMemberShipDataOperationCompleted == null)) {
                this.GetMemberShipDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMemberShipDataOperationCompleted);
            }
            this.InvokeAsync("GetMemberShipData", new object[] {
                        premember,
                        membno}, this.GetMemberShipDataOperationCompleted, userState);
        }
        
        private void OnGetMemberShipDataOperationCompleted(object arg) {
            if ((this.GetMemberShipDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMemberShipDataCompleted(this, new GetMemberShipDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMemberDetails", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ICSIData GetMemberDetails(string value) {
            object[] results = this.Invoke("GetMemberDetails", new object[] {
                        value});
            return ((ICSIData)(results[0]));
        }
        
        /// <remarks/>
        public void GetMemberDetailsAsync(string value) {
            this.GetMemberDetailsAsync(value, null);
        }
        
        /// <remarks/>
        public void GetMemberDetailsAsync(string value, object userState) {
            if ((this.GetMemberDetailsOperationCompleted == null)) {
                this.GetMemberDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMemberDetailsOperationCompleted);
            }
            this.InvokeAsync("GetMemberDetails", new object[] {
                        value}, this.GetMemberDetailsOperationCompleted, userState);
        }
        
        private void OnGetMemberDetailsOperationCompleted(object arg) {
            if ((this.GetMemberDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMemberDetailsCompleted(this, new GetMemberDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMemberDetailsOnline", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ICSIDataOnline GetMemberDetailsOnline(string MembershipNo, System.DateTime DOB) {
            object[] results = this.Invoke("GetMemberDetailsOnline", new object[] {
                        MembershipNo,
                        DOB});
            return ((ICSIDataOnline)(results[0]));
        }
        
        /// <remarks/>
        public void GetMemberDetailsOnlineAsync(string MembershipNo, System.DateTime DOB) {
            this.GetMemberDetailsOnlineAsync(MembershipNo, DOB, null);
        }
        
        /// <remarks/>
        public void GetMemberDetailsOnlineAsync(string MembershipNo, System.DateTime DOB, object userState) {
            if ((this.GetMemberDetailsOnlineOperationCompleted == null)) {
                this.GetMemberDetailsOnlineOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMemberDetailsOnlineOperationCompleted);
            }
            this.InvokeAsync("GetMemberDetailsOnline", new object[] {
                        MembershipNo,
                        DOB}, this.GetMemberDetailsOnlineOperationCompleted, userState);
        }
        
        private void OnGetMemberDetailsOnlineOperationCompleted(object arg) {
            if ((this.GetMemberDetailsOnlineCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMemberDetailsOnlineCompleted(this, new GetMemberDetailsOnlineCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetStudentDetails", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ICSIData GetStudentDetails(string value) {
            object[] results = this.Invoke("GetStudentDetails", new object[] {
                        value});
            return ((ICSIData)(results[0]));
        }
        
        /// <remarks/>
        public void GetStudentDetailsAsync(string value) {
            this.GetStudentDetailsAsync(value, null);
        }
        
        /// <remarks/>
        public void GetStudentDetailsAsync(string value, object userState) {
            if ((this.GetStudentDetailsOperationCompleted == null)) {
                this.GetStudentDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStudentDetailsOperationCompleted);
            }
            this.InvokeAsync("GetStudentDetails", new object[] {
                        value}, this.GetStudentDetailsOperationCompleted, userState);
        }
        
        private void OnGetStudentDetailsOperationCompleted(object arg) {
            if ((this.GetStudentDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStudentDetailsCompleted(this, new GetStudentDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetStudentDetailsForeMSOP", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ICSIData GetStudentDetailsForeMSOP(string value) {
            object[] results = this.Invoke("GetStudentDetailsForeMSOP", new object[] {
                        value});
            return ((ICSIData)(results[0]));
        }
        
        /// <remarks/>
        public void GetStudentDetailsForeMSOPAsync(string value) {
            this.GetStudentDetailsForeMSOPAsync(value, null);
        }
        
        /// <remarks/>
        public void GetStudentDetailsForeMSOPAsync(string value, object userState) {
            if ((this.GetStudentDetailsForeMSOPOperationCompleted == null)) {
                this.GetStudentDetailsForeMSOPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStudentDetailsForeMSOPOperationCompleted);
            }
            this.InvokeAsync("GetStudentDetailsForeMSOP", new object[] {
                        value}, this.GetStudentDetailsForeMSOPOperationCompleted, userState);
        }
        
        private void OnGetStudentDetailsForeMSOPOperationCompleted(object arg) {
            if ((this.GetStudentDetailsForeMSOPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStudentDetailsForeMSOPCompleted(this, new GetStudentDetailsForeMSOPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMemberName", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetMemberName(string value) {
            object[] results = this.Invoke("GetMemberName", new object[] {
                        value});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetMemberNameAsync(string value) {
            this.GetMemberNameAsync(value, null);
        }
        
        /// <remarks/>
        public void GetMemberNameAsync(string value, object userState) {
            if ((this.GetMemberNameOperationCompleted == null)) {
                this.GetMemberNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMemberNameOperationCompleted);
            }
            this.InvokeAsync("GetMemberName", new object[] {
                        value}, this.GetMemberNameOperationCompleted, userState);
        }
        
        private void OnGetMemberNameOperationCompleted(object arg) {
            if ((this.GetMemberNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMemberNameCompleted(this, new GetMemberNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetStudentName", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ICSIData GetStudentName(string value) {
            object[] results = this.Invoke("GetStudentName", new object[] {
                        value});
            return ((ICSIData)(results[0]));
        }
        
        /// <remarks/>
        public void GetStudentNameAsync(string value) {
            this.GetStudentNameAsync(value, null);
        }
        
        /// <remarks/>
        public void GetStudentNameAsync(string value, object userState) {
            if ((this.GetStudentNameOperationCompleted == null)) {
                this.GetStudentNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStudentNameOperationCompleted);
            }
            this.InvokeAsync("GetStudentName", new object[] {
                        value}, this.GetStudentNameOperationCompleted, userState);
        }
        
        private void OnGetStudentNameOperationCompleted(object arg) {
            if ((this.GetStudentNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStudentNameCompleted(this, new GetStudentNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetStudentData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ICSIData GetStudentData(string value, string DOB) {
            object[] results = this.Invoke("GetStudentData", new object[] {
                        value,
                        DOB});
            return ((ICSIData)(results[0]));
        }
        
        /// <remarks/>
        public void GetStudentDataAsync(string value, string DOB) {
            this.GetStudentDataAsync(value, DOB, null);
        }
        
        /// <remarks/>
        public void GetStudentDataAsync(string value, string DOB, object userState) {
            if ((this.GetStudentDataOperationCompleted == null)) {
                this.GetStudentDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStudentDataOperationCompleted);
            }
            this.InvokeAsync("GetStudentData", new object[] {
                        value,
                        DOB}, this.GetStudentDataOperationCompleted, userState);
        }
        
        private void OnGetStudentDataOperationCompleted(object arg) {
            if ((this.GetStudentDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStudentDataCompleted(this, new GetStudentDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ICSI {
        
        private string membershipNoField;
        
        private string dateofBirthField;
        
        private string firstNameField;
        
        private string middleNameField;
        
        private string lastNameField;
        
        private string premembnoField;
        
        private string barredMemberField;
        
        private string barredDateField;
        
        private string enrollDateField;
        
        private string certificateofPracticalNumberField;
        
        private string cPDateField;
        
        private string nameField;
        
        private string emailIDField;
        
        private string memberStatusField;
        
        private string mSgField;
        
        /// <remarks/>
        public string MembershipNo {
            get {
                return this.membershipNoField;
            }
            set {
                this.membershipNoField = value;
            }
        }
        
        /// <remarks/>
        public string DateofBirth {
            get {
                return this.dateofBirthField;
            }
            set {
                this.dateofBirthField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string MiddleName {
            get {
                return this.middleNameField;
            }
            set {
                this.middleNameField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string premembno {
            get {
                return this.premembnoField;
            }
            set {
                this.premembnoField = value;
            }
        }
        
        /// <remarks/>
        public string BarredMember {
            get {
                return this.barredMemberField;
            }
            set {
                this.barredMemberField = value;
            }
        }
        
        /// <remarks/>
        public string BarredDate {
            get {
                return this.barredDateField;
            }
            set {
                this.barredDateField = value;
            }
        }
        
        /// <remarks/>
        public string EnrollDate {
            get {
                return this.enrollDateField;
            }
            set {
                this.enrollDateField = value;
            }
        }
        
        /// <remarks/>
        public string CertificateofPracticalNumber {
            get {
                return this.certificateofPracticalNumberField;
            }
            set {
                this.certificateofPracticalNumberField = value;
            }
        }
        
        /// <remarks/>
        public string CPDate {
            get {
                return this.cPDateField;
            }
            set {
                this.cPDateField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string EmailID {
            get {
                return this.emailIDField;
            }
            set {
                this.emailIDField = value;
            }
        }
        
        /// <remarks/>
        public string MemberStatus {
            get {
                return this.memberStatusField;
            }
            set {
                this.memberStatusField = value;
            }
        }
        
        /// <remarks/>
        public string MSg {
            get {
                return this.mSgField;
            }
            set {
                this.mSgField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ICSIDataOnline {
        
        private string nameField;
        
        private string emailField;
        
        private string mobileField;
        
        private string addressField;
        
        private string cityField;
        
        private string mSgField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string Mobile {
            get {
                return this.mobileField;
            }
            set {
                this.mobileField = value;
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string MSg {
            get {
                return this.mSgField;
            }
            set {
                this.mSgField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ICSIData {
        
        private string nameField;
        
        private string emailField;
        
        private string mobileField;
        
        private string regionField;
        
        private string chapterField;
        
        private string mSgField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string Mobile {
            get {
                return this.mobileField;
            }
            set {
                this.mobileField = value;
            }
        }
        
        /// <remarks/>
        public string Region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
            }
        }
        
        /// <remarks/>
        public string Chapter {
            get {
                return this.chapterField;
            }
            set {
                this.chapterField = value;
            }
        }
        
        /// <remarks/>
        public string MSg {
            get {
                return this.mSgField;
            }
            set {
                this.mSgField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetMemberShipDataForGSTCompletedEventHandler(object sender, GetMemberShipDataForGSTCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMemberShipDataForGSTCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMemberShipDataForGSTCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ICSI Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ICSI)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetMemberDataCompletedEventHandler(object sender, GetMemberDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMemberDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMemberDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ICSI Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ICSI)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetMemberShipDataCompletedEventHandler(object sender, GetMemberShipDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMemberShipDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMemberShipDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ICSI Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ICSI)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetMemberDetailsCompletedEventHandler(object sender, GetMemberDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMemberDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMemberDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ICSIData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ICSIData)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetMemberDetailsOnlineCompletedEventHandler(object sender, GetMemberDetailsOnlineCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMemberDetailsOnlineCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMemberDetailsOnlineCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ICSIDataOnline Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ICSIDataOnline)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetStudentDetailsCompletedEventHandler(object sender, GetStudentDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStudentDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStudentDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ICSIData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ICSIData)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetStudentDetailsForeMSOPCompletedEventHandler(object sender, GetStudentDetailsForeMSOPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStudentDetailsForeMSOPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStudentDetailsForeMSOPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ICSIData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ICSIData)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetMemberNameCompletedEventHandler(object sender, GetMemberNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMemberNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMemberNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetStudentNameCompletedEventHandler(object sender, GetStudentNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStudentNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStudentNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ICSIData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ICSIData)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetStudentDataCompletedEventHandler(object sender, GetStudentDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStudentDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStudentDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ICSIData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ICSIData)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591