//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICSI_UDIN.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ICSI_DBModleEntities : DbContext
    {
        public ICSI_DBModleEntities()
            : base("name=ICSI_DBModleEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblCertificateType> tblCertificateTypes { get; set; }
        public virtual DbSet<tblComplaint> tblComplaints { get; set; }
        public virtual DbSet<tblDocParticular> tblDocParticulars { get; set; }
        public virtual DbSet<tblDocumentType> tblDocumentTypes { get; set; }
        public virtual DbSet<tblErrorLog> tblErrorLogs { get; set; }
        public virtual DbSet<tblStatu> tblStatus { get; set; }
        public virtual DbSet<tblUDIN> tblUDINs { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
        public virtual DbSet<tblUserActivity> tblUserActivities { get; set; }
    
        public virtual ObjectResult<RP_GetUDINList_Result> RP_GetUDINList(string uDINNumber)
        {
            var uDINNumberParameter = uDINNumber != null ?
                new ObjectParameter("UDINNumber", uDINNumber) :
                new ObjectParameter("UDINNumber", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RP_GetUDINList_Result>("RP_GetUDINList", uDINNumberParameter);
        }
    
        public virtual ObjectResult<RP_UDINVerification_Result> RP_UDINVerification(string fName, string mobileNumber, string emailId, string membershipNumber)
        {
            var fNameParameter = fName != null ?
                new ObjectParameter("FName", fName) :
                new ObjectParameter("FName", typeof(string));
    
            var mobileNumberParameter = mobileNumber != null ?
                new ObjectParameter("MobileNumber", mobileNumber) :
                new ObjectParameter("MobileNumber", typeof(string));
    
            var emailIdParameter = emailId != null ?
                new ObjectParameter("EmailId", emailId) :
                new ObjectParameter("EmailId", typeof(string));
    
            var membershipNumberParameter = membershipNumber != null ?
                new ObjectParameter("MembershipNumber", membershipNumber) :
                new ObjectParameter("MembershipNumber", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RP_UDINVerification_Result>("RP_UDINVerification", fNameParameter, mobileNumberParameter, emailIdParameter, membershipNumberParameter);
        }
    }
}
