//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICSI_UDIN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblComplaint
    {
        public int ID { get; set; }
        public string MembershipNumber { get; set; }
        public string EmailId { get; set; }
        public string MobileNumber { get; set; }
        public string ComplaintDesc { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
