//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICSI_UDIN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUDIN
    {
        public int ID { get; set; }
        public string MembershipNumber { get; set; }
        public Nullable<int> YearOfEnrollment { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string UDINUniqueCode { get; set; }
        public string IsValid { get; set; }
        public Nullable<int> DocumentTypeId { get; set; }
        public string DocumentDescription { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> UserId { get; set; }
    }
}
