//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICSI_UDIN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUDIN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblUDIN()
        {
            this.tblRevokeUDINs = new HashSet<tblRevokeUDIN>();
        }
    
        public int ID { get; set; }
        public string MembershipNumber { get; set; }
        public Nullable<int> YearOfEnrollment { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string UDINUniqueCode { get; set; }
        public string IsValid { get; set; }
        public Nullable<int> DocumentTypeId { get; set; }
        public string DocumentDescription { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string FinancialYear { get; set; }
        public string ClientName { get; set; }
        public string CINNumber { get; set; }
        public int CertificateTypeId { get; set; }
        public int UDINInitiative { get; set; }
        public System.DateTime DateOfSigningDoc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRevokeUDIN> tblRevokeUDINs { get; set; }
    }
}
